// Generated by Wrangler on Sun Sep 08 2024 23:37:24 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	LOCAL_DATE: string;
	SITE_URL: string;
}
