// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	VITE_LOCAL_DATE: string;
	SITE_URL: string;
	R2_ACCESS_KEY: string;
	R2_SECRET_KEY: string;
	R2_ENDPOINT: string;
}
